name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # TODO: add nightly deploy

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Base path of GH Pages deployment
  # All links will be relative to this path
  BASE_PATH: "/spack_cache"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Get Data
        run: uv run data.py

      - name: Build Static Pages
        run: uv run build.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./_build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
